[build-system]
requires = ["setuptools>=69.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "social-fastapi"
version = "0.1.0"
description = "FastAPI social API"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "fastapi[standard]>=0.111.0,<1.0.0",
  "uvicorn[standard]>=0.30.0,<0.31.0",
  "sqlalchemy>=2.0.30,<3.0.0",
  "psycopg2-binary>=2.9.0,<3.0.0",
  "passlib[bcrypt]>=1.7.4,<2.0.0",
  "bcrypt==4.0.1",
  "python-jose[cryptography]>=3.3.0,<4.0.0",
  "pydantic>=2.7.0,<3.0.0",
  "pydantic-settings>=2.3.0,<3.0.0",
  "email-validator>=2.1.0,<3.0.0",
  "alembic>=1.13.0,<2.0.0",
  "python-multipart>=0.0.9,<1.0.0",
]

[project.urls]
Homepage = "https://github.com/mharmainw/social_fastapi"

[dependency-groups]
dev = [
  "pytest>=8.0.0,<9.0.0",
  "httpx>=0.27.0,<1.0.0"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["app*", "alembic*"]

[tool.fastapi]
entrypoint = "app.main:app"
